#!/usr/bin/python3

from sys import argv
prime = __import__("0-fac").is_prime

b = argv[1]
with open(b) as f1:
    while True:
        c = f1.readline()
        if not c:
            break
        c = int(c)
        for i in range(2, c):
            a = int(c / i)
            if c % i == 0 and prime(a):
                print("{} * {} = {}".format(a, i, c))
                break
